import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import data from "../../data/education.json";
import { useState } from "react";
import Card from "../../components/Card";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [information, setInformation] = useState([...data]);

  return (
    <>
      <Head>
        <title>In Class Examples</title>
        <meta name="description" content="Generated by create next app" />w
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href="about" className={styles.about}>
          Employees
        </Link>
        <h1 className={styles.programs}>Programs</h1>
        <div className={styles.maindatawrapper}>
          <div className={styles.businesswrapper}>
            <h2 className={styles.businesstitle}>Business</h2>
            {information &&
              information.map((info, index) => {
                if (info.department.toLowerCase() === "business") {
                  return <Card key={index} degree={info.degree} />;
                }
              })}
          </div>
          <div className={styles.computingwrapper}>
            <h2 className={styles.computingtitle}>Computing</h2>
            {information &&
              information.map((info, index) => {
                if (info.department.toLowerCase() === "computing") {
                  return <Card key={index} degree={info.degree} />;
                }
              })}
          </div>
        </div>
      </main>
    </>
  );
}
